#! /usr/bin/bash
#SBATCH --partition=gpu
#SBATCH --job-name=Compilation_TomoBayes
#SBATCH --output=output_compilation.log
#SBATCH --error=error_compilation.log
#SBATCH --mail-user=nicolas.gac@l2s.centralesupelec.fr
##SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --mem=16G
##SBATCH --time=30:00:00
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
source compilation.sh 
